void menu();
void insertItens();
char *** insertItensAfterFile();
void writeFile(char *tableName, char *itemTable, char *operation);
void showTables();
void deleteTable();
void deleteItemTable();
void search();
char ***fileToMatrix(char *tableName);
int *tableMetadata(char *tableName);
